### ISSUE TITLE
Git Clone and Game

### ISSUE THREAD

**Issue by Mubeenkh** [JamesKawashima/The_Dweller_left_Adrift#1]
Hey guys, 
I hope this issue is just on my side. When I cloned the repository to test the game, everything was fine. However, the game was blank, there was nothing there, just the white background like when you start a new project. Also, when I git clone, it took more than 10 minutes to clone the repository.

*Next day: I'm trying to clone it at Vanier this time and its passed 15 min and its still not done cloning

**Comment by Justophil** [comment]
The only thing that i can say that it might just be on your side, because when we clone on our side we have everything working.
It can maybe be the fact that the file is too big for it to clone
