### ISSUE TITLE
lssue

### ISSUE THREAD

**Issue by spacexplorpurr** [JamesKawashima/The_Dweller_left_Adrift#2]

**Comment by spacexplorpurr** [comment]
Hey guys,
You might already know and you might already be working on it but I'll mention just in case. 
When you go into credits, you can't go back to the main menu; the arrow to go back doesn't work. You can easily fix it by doing what you did for the options menu with controls instructions (because the arrow to go back works there).
- Alston

**Comment by spacexplorpurr** [comment]
Also,
When the player goes off screen (left or right), he disappears when you bring him back. 
- Alston

**Comment by Justophil** [comment]
We just finished correcting both issues, thank you for letting us know!
